name: Clarive MSBuild Plugin
description: The MSBuild plugin will allow you to build applications via the command-line (CLI).
version: 1.0
icon: https://github.com/clarive/cla-msbuild-plugin/public/icon/msbuild.svg
url: https://github.com/clarive/cla-msbuild-plugin
requires:
  - clarive_version: 6.8 <= version
dependencies:
  - cla-msbuild-plugin
